version: '3.8'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - site_output:/app/_site
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - site_output:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - builder
volumes:
  site_output:
